ZABBIX_VERSION_MAJOR = "5.4"
POSTGRES_VERSION = "13"
HOSTNAME='postgres-server'

require 'getoptlong'

ZABBIX_SERVER=ENV['ZABBIX_SERVER'] || "127.0.0.1"

Vagrant.configure("2") do |config|
	config.vm.define "postgres-server" do |zabbix|

		config.vm.box = "generic/debian10"

		zabbix.vm.hostname = "#{HOSTNAME}"

		zabbix.vm.provision "shell", inline: <<-SHELL
			echo '----Installing Debian dependencies---- '
			sudo apt-get -q -y install gnupg2
			SHELL

		zabbix.vm.provision "shell", inline: <<-SHELL
			echo '----Installing PostgreSQL---- '
			sudo echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
			wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
			sudo apt-get -q update
			sudo apt-get -q -y install postgresql-#{POSTGRES_VERSION}
			sudo systemctl enable --now postgresql@#{POSTGRES_VERSION}-main
			SHELL

		zabbix.vm.provision "shell", inline: <<-SHELL
			echo '----Configuring and starting PostgreSQL---- '
			sudo sed -i "s/ident/md5/g" /etc/postgresql/#{POSTGRES_VERSION}/main/pg_hba.conf
			sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /etc/postgresql/#{POSTGRES_VERSION}/main/postgresql.conf
			sudo systemctl restart postgresql@#{POSTGRES_VERSION}-main
			echo '----Creating database and user---- '
			sudo -u postgres psql -c "CREATE USER zabbix WITH ENCRYPTED PASSWORD 'Z4bb1xD4t4b4s3'" 2>/dev/null
			sudo -u postgres createdb -O zabbix -E Unicode -T template0 zabbix 2>/dev/null
			SHELL

		zabbix.vm.provision "shell", inline: <<-SHELL
			echo '----Installing Zabbix Agent---- '
			cd /tmp
			wget --quiet https://repo.zabbix.com/zabbix/#{ZABBIX_VERSION_MAJOR}/debian/pool/main/z/zabbix-release/zabbix-release_#{ZABBIX_VERSION_MAJOR}-1+debian10_all.deb
			sudo dpkg -i zabbix-release_#{ZABBIX_VERSION_MAJOR}-1+debian10_all.deb
			sudo apt-get -q update
			sudo apt-get -q -y install zabbix-agent2

			sudo sh -c "sed -i 's/Server=127.0.0.1/Server=#{ZABBIX_SERVER}/' /etc/zabbix/zabbix_agent2.conf"
			sudo sh -c "sed -i 's/ServerActive=127.0.0.1/ServerActive=#{ZABBIX_SERVER}/' /etc/zabbix/zabbix_agent2.conf"
			sudo sh -c "sed -i 's/Hostname=Zabbix\ server/Hostname=#{HOSTNAME}-'$(ifconfig eth0 | grep 'inet' | cut -d: -f2 | awk '{ print $2}')'/' /etc/zabbix/zabbix_agent2.conf"
			SHELL

		zabbix.vm.provision "shell", inline: <<-SHELL
			echo '----Creating user for zabbix-agent2 in PostgreSQL---- '
			sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /etc/postgresql/#{POSTGRES_VERSION}/main/postgresql.conf
			
			sudo cp /etc/postgresql/#{POSTGRES_VERSION}/main/pg_hba.conf /etc/postgresql/#{POSTGRES_VERSION}/main/pg_hba.conf.orig
			sudo sh -c "echo 'local all postgres peer' > /etc/postgresql/#{POSTGRES_VERSION}/main/pg_hba.conf"
			sudo sh -c "echo 'host all all 127.0.0.1/32 trust' >> /etc/postgresql/#{POSTGRES_VERSION}/main/pg_hba.conf"
			
			sudo systemctl restart postgresql@#{POSTGRES_VERSION}-main			
			
			sudo -u postgres psql -c "CREATE USER postgres WITH ENCRYPTED PASSWORD 'postgres'" 2>/dev/null
			sudo -u postgres psql -c "GRANT SELECT ON pg_stat_database TO zbx_monitor;" 2>/dev/null			
			sudo -u postgres psql -c "ALTER USER zbx_monitor WITH SUPERUSER;" 2>/dev/null
			SHELL

		zabbix.vm.provision "shell", inline: <<-SHELL	
			echo '----Starting Zabbix Agent---- '
			sudo systemctl restart zabbix-agent2
			sudo systemctl enable zabbix-agent2
			SHELL

		zabbix.vm.provision "shell", inline: <<-SHELL
			sudo rm -rf /var/lib/apt/lists/*
			sudo rm -rf /tmp/*
			SHELL

	end

end