ZABBIX_VERSION_MAJOR = "5.4"
HOSTNAME='apache-server'

require 'getoptlong'

ZABBIX_SERVER=ENV['ZABBIX_SERVER'] || "127.0.0.1"

Vagrant.configure("2") do |config|
	config.vm.define "apache-server" do |zabbix|

		config.vm.box = "generic/debian10"

		zabbix.vm.hostname = "#{HOSTNAME}"

		zabbix.vm.provision "shell", inline: <<-SHELL
			echo '----Installing Debian dependencies---- '
			sudo apt-get -q -y install gnupg2
			SHELL

		zabbix.vm.provision "shell", inline: <<-SHELL
			echo '----Installing apache---- '
			sudo apt-get -q -y install apache2
			sudo systemctl enable --now apache2
			SHELL

		zabbix.vm.provision "shell", inline: <<-SHELL
			echo '----Installing Zabbix Agent---- '
			cd /tmp
			wget --quiet https://repo.zabbix.com/zabbix/#{ZABBIX_VERSION_MAJOR}/debian/pool/main/z/zabbix-release/zabbix-release_#{ZABBIX_VERSION_MAJOR}-1+debian10_all.deb
			sudo dpkg -i zabbix-release_#{ZABBIX_VERSION_MAJOR}-1+debian10_all.deb
			sudo apt-get -q update
			sudo apt-get -q -y install zabbix-agent2

			sudo sh -c "sed -i 's/Server=127.0.0.1/Server=#{ZABBIX_SERVER}/' /etc/zabbix/zabbix_agent2.conf"
			sudo sh -c "sed -i 's/ServerActive=127.0.0.1/ServerActive=#{ZABBIX_SERVER}/' /etc/zabbix/zabbix_agent2.conf"
			sudo sh -c "sed -i 's/Hostname=Zabbix\ server/Hostname=#{HOSTNAME}-'$(ifconfig eth0 | grep 'inet' | cut -d: -f2 | awk '{ print $2}')'/' /etc/zabbix/zabbix_agent2.conf"
			
			echo '----Starting Zabbix Agent---- '
			sudo systemctl restart zabbix-agent2
			sudo systemctl enable zabbix-agent2
			SHELL

		zabbix.vm.provision "shell", inline: <<-SHELL
			sudo rm -rf /var/lib/apt/lists/*
			sudo rm -rf /tmp/*
			SHELL

	end

end